spring.application.name=tiffino_user_menu

server.port=8082

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/tiffino_user_admin_menu?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shubham@1011
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# spring.mvc.view.prefix=/WEB-INF/jsp/
# spring.mvc.view.suffix=.jsp
